name: ci
on:
    pull_request:
        branches: [main]
    push:
        branches: [main]
jobs:
    testing:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '18'
            - name: Run Node app
              run: node index.js &
            - name: Testing of the node app
              run: |
                sleep 5
                curl -f http://localhost:3000
