name: ci
on:
    pull_request:
        branches: [main]
    push:
        branches: [main]
jobs:
    testing:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '18'
            - name: Run Node app
              run: node index.js &
            - name: Testing of the node app
              run: |
                sleep 5
                curl -f http://localhost:3000

    build:
        runs-on: ubuntu-latest
        needs: testing

        steps:
            - name: login to docker hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME}}
                password: ${{ secrets.DOCKER_PASSWORD}}

            - name: Checkout code
              uses: actions/checkout@v4
            - name: build docker image
              run: docker build -t nodeapp-project2:latest .
            - name: push to the dockerhub
              run: docker push nnekic/nodeapp-project2:latest